# Generated by Django 2.0.2 on 2018-03-31 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='customer',
            name='locality',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='customer',
            name='main_address',
            field=models.TextField(max_length=128),
        ),
    ]
