package modelos;
// Generated 24/11/2019 10:52:28 AM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;

/**
 * Almacen generated by hbm2java
 */
public class Almacen  implements java.io.Serializable {


     private int idalmacen;
     private Municipio municipio;
     private Tienda tienda;
     private String nombre;
     @JsonIgnore
     private Set tareawebscrapers = new HashSet(0);

    public Almacen() {
    }

	
    public Almacen(int idalmacen, Tienda tienda, String nombre) {
        this.idalmacen = idalmacen;
        this.tienda = tienda;
        this.nombre = nombre;
    }
    public Almacen(int idalmacen, Municipio municipio, Tienda tienda, String nombre, Set tareawebscrapers) {
       this.idalmacen = idalmacen;
       this.municipio = municipio;
       this.tienda = tienda;
       this.nombre = nombre;
       this.tareawebscrapers = tareawebscrapers;
    }
   
    public int getIdalmacen() {
        return this.idalmacen;
    }
    
    public void setIdalmacen(int idalmacen) {
        this.idalmacen = idalmacen;
    }
    public Municipio getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(Municipio municipio) {
        this.municipio = municipio;
    }
    public Tienda getTienda() {
        return this.tienda;
    }
    
    public void setTienda(Tienda tienda) {
        this.tienda = tienda;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getTareawebscrapers() {
        return this.tareawebscrapers;
    }
    
    public void setTareawebscrapers(Set tareawebscrapers) {
        this.tareawebscrapers = tareawebscrapers;
    }




}


