package modelos;
// Generated 26/11/2019 06:43:24 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private int iddepartamento;
     private Short indicativo;
     private Short estado;
     private String nombredepartamento;
     @JsonIgnore
     private Set usuarioDireccions = new HashSet(0);
     @JsonIgnore
     private Set municipios = new HashSet(0);

    public Departamento() {
    }

	
    public Departamento(int iddepartamento) {
        this.iddepartamento = iddepartamento;
    }
    public Departamento(int iddepartamento, Short indicativo, Short estado, String nombredepartamento, Set usuarioDireccions, Set municipios) {
       this.iddepartamento = iddepartamento;
       this.indicativo = indicativo;
       this.estado = estado;
       this.nombredepartamento = nombredepartamento;
       this.usuarioDireccions = usuarioDireccions;
       this.municipios = municipios;
    }
   
    public int getIddepartamento() {
        return this.iddepartamento;
    }
    
    public void setIddepartamento(int iddepartamento) {
        this.iddepartamento = iddepartamento;
    }
    public Short getIndicativo() {
        return this.indicativo;
    }
    
    public void setIndicativo(Short indicativo) {
        this.indicativo = indicativo;
    }
    public Short getEstado() {
        return this.estado;
    }
    
    public void setEstado(Short estado) {
        this.estado = estado;
    }
    public String getNombredepartamento() {
        return this.nombredepartamento;
    }
    
    public void setNombredepartamento(String nombredepartamento) {
        this.nombredepartamento = nombredepartamento;
    }
    public Set getUsuarioDireccions() {
        return this.usuarioDireccions;
    }
    
    public void setUsuarioDireccions(Set usuarioDireccions) {
        this.usuarioDireccions = usuarioDireccions;
    }
    public Set getMunicipios() {
        return this.municipios;
    }
    
    public void setMunicipios(Set municipios) {
        this.municipios = municipios;
    }




}


