package modelos;
// Generated 25/11/2019 06:05:58 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.OneToMany;

/**
 * Lista generated by hbm2java
 */
public class Lista  implements java.io.Serializable {


     private int idlista;
     @JsonIgnore
     private Usuario usuario;
     @JsonIgnore
     private UsuarioDireccion usuarioDireccion;
     private Date fechacreada;
     private Short estado;
     private String nombrelista;
     private Set listasCompartidases = new HashSet(0);
     @OneToMany(cascade = CascadeType.ALL, mappedBy = "post",orphanRemoval = true)
     @JsonIgnore  
     private Set listaProductos = new HashSet(0);

    public Lista() {
    }

	
    public Lista(int idlista) {
        this.idlista = idlista;
    }
    public Lista(int idlista, Usuario usuario, UsuarioDireccion usuarioDireccion, Date fechacreada, Short estado, String nombrelista, Set listasCompartidases, Set listaProductos) {
       this.idlista = idlista;
       this.usuario = usuario;
       this.usuarioDireccion = usuarioDireccion;
       this.fechacreada = fechacreada;
       this.estado = estado;
       this.nombrelista = nombrelista;
       this.listasCompartidases = listasCompartidases;
       this.listaProductos = listaProductos;
    }
   
    public int getIdlista() {
        return this.idlista;
    }
    
    public void setIdlista(int idlista) {
        this.idlista = idlista;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public UsuarioDireccion getUsuarioDireccion() {
        return this.usuarioDireccion;
    }
    
    public void setUsuarioDireccion(UsuarioDireccion usuarioDireccion) {
        this.usuarioDireccion = usuarioDireccion;
    }
    public Date getFechacreada() {
        return this.fechacreada;
    }
    
    public void setFechacreada(Date fechacreada) {
        this.fechacreada = fechacreada;
    }
    public Short getEstado() {
        return this.estado;
    }
    
    public void setEstado(Short estado) {
        this.estado = estado;
    }
    public String getNombrelista() {
        return this.nombrelista;
    }
    
    public void setNombrelista(String nombrelista) {
        this.nombrelista = nombrelista;
    }
    public Set getListasCompartidases() {
        return this.listasCompartidases;
    }
    
    public void setListasCompartidases(Set listasCompartidases) {
        this.listasCompartidases = listasCompartidases;
    }
    public Set getListaProductos() {
        return this.listaProductos;
    }
    
    public void setListaProductos(Set listaProductos) {
        this.listaProductos = listaProductos;
    }




}


