package modelos;
// Generated 25/11/2019 06:05:58 PM by Hibernate Tools 4.3.1



/**
 * ListaProductoNew generated by hbm2java
 */
public class ListaProductoNew  implements java.io.Serializable {


     private int id;
     private Integer idlista;
     private Integer idproducto;
     private String nombreproducto;
     private String descripcion;
     private String precioproducto;
     private String url;

    public ListaProductoNew() {
    }

	
    public ListaProductoNew(int id) {
        this.id = id;
    }
    public ListaProductoNew(int id, Integer idlista, Integer idproducto, String nombreproducto, String descripcion, String precioproducto, String url) {
       this.id = id;
       this.idlista = idlista;
       this.idproducto = idproducto;
       this.nombreproducto = nombreproducto;
       this.descripcion = descripcion;
       this.precioproducto = precioproducto;
       this.url = url;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getIdlista() {
        return this.idlista;
    }
    
    public void setIdlista(Integer idlista) {
        this.idlista = idlista;
    }
    public Integer getIdproducto() {
        return this.idproducto;
    }
    
    public void setIdproducto(Integer idproducto) {
        this.idproducto = idproducto;
    }
    public String getNombreproducto() {
        return this.nombreproducto;
    }
    
    public void setNombreproducto(String nombreproducto) {
        this.nombreproducto = nombreproducto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getPrecioproducto() {
        return this.precioproducto;
    }
    
    public void setPrecioproducto(String precioproducto) {
        this.precioproducto = precioproducto;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


