package modelos;
// Generated 24/11/2019 10:52:28 AM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.Date;

/**
 * ListaProducto generated by hbm2java
 */
public class ListaProducto  implements java.io.Serializable {


     private int idlistaproducto;
     @JsonIgnore
     private Lista lista;
     @JsonIgnore
     private Producto producto;
     private String nombreproducto;
     private String descripcionproducto;
     private Double precioproducto;
     private String url;
     private String direccionproducto;
     private Date fechaagregado;
private int producto_idproducto;
    public ListaProducto() {
    }

	
    public ListaProducto(int idlistaproducto) {
        this.idlistaproducto = idlistaproducto;
    }
    public ListaProducto(int idlistaproducto, Lista lista, Producto producto, String nombreproducto, String descripcionproducto, Double precioproducto, String url, String direccionproducto, Date fechaagregado) {
       this.idlistaproducto = idlistaproducto;
       this.lista = lista;
       this.producto = producto;
       this.nombreproducto = nombreproducto;
       this.descripcionproducto = descripcionproducto;
       this.precioproducto = precioproducto;
       this.url = url;
       this.direccionproducto = direccionproducto;
       this.fechaagregado = fechaagregado;
    }
   
    public int getIdlistaproducto() {
        return this.idlistaproducto;
    }
    
    public void setIdlistaproducto(int idlistaproducto) {
        this.idlistaproducto = idlistaproducto;
    }
    public Lista getLista() {
        return this.lista;
    }
    
    public void setLista(Lista lista) {
        this.lista = lista;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public String getNombreproducto() {
        return this.nombreproducto;
    }
    
    public void setNombreproducto(String nombreproducto) {
        this.nombreproducto = nombreproducto;
    }
    public String getDescripcionproducto() {
        return this.descripcionproducto;
    }
    
    public void setDescripcionproducto(String descripcionproducto) {
        this.descripcionproducto = descripcionproducto;
    }
    public Double getPrecioproducto() {
        return this.precioproducto;
    }
    
    public void setPrecioproducto(Double precioproducto) {
        this.precioproducto = precioproducto;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getDireccionproducto() {
        return this.direccionproducto;
    }
    
    public void setDireccionproducto(String direccionproducto) {
        this.direccionproducto = direccionproducto;
    }
    public Date getFechaagregado() {
        return this.fechaagregado;
    }
    
    public void setFechaagregado(Date fechaagregado) {
        this.fechaagregado = fechaagregado;
    }
    
public int getProducto_idproducto() {
        return this.producto_idproducto;
    }

    public void setProducto_idproducto(int producto_idproducto) {
        this.producto_idproducto = producto_idproducto;
    }  



}


