package modelos;
// Generated 25/11/2019 06:05:58 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ListaNew generated by hbm2java
 */
public class ListaNew  implements java.io.Serializable {


     private int id;
     private Date fechacreada;
     private String idusuario;
     private String nombrelista;

    public ListaNew() {
    }

	
    public ListaNew(int id, String idusuario) {
        this.id = id;
        this.idusuario = idusuario;
    }
    public ListaNew(int id, Date fechacreada, String idusuario, String nombrelista) {
       this.id = id;
       this.fechacreada = fechacreada;
       this.idusuario = idusuario;
       this.nombrelista = nombrelista;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getFechacreada() {
        return this.fechacreada;
    }
    
    public void setFechacreada(Date fechacreada) {
        this.fechacreada = fechacreada;
    }
    public String getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(String idusuario) {
        this.idusuario = idusuario;
    }
    public String getNombrelista() {
        return this.nombrelista;
    }
    
    public void setNombrelista(String nombrelista) {
        this.nombrelista = nombrelista;
    }




}


