package modelos;
// Generated 30/11/2019 06:41:14 PM by Hibernate Tools 4.3.1



/**
 * ListaProductoNew generated by hbm2java
 */
public class ListaProductoNew  implements java.io.Serializable {


     private int id;
     private Integer idlista;
     private Integer idproducto;
     private String nombreproducto;
     private String descripcion;
     private String precioproducto;
     private String url;
     private Integer items;
     private String imagen;
     private String relaciones;
     private String tiendaNombre;
     private Double precioDob;
     private Double ahorro;

    public ListaProductoNew() {
    }

	
    public ListaProductoNew(int id) {
        this.id = id;
    }
    public ListaProductoNew(int id, Integer idlista, Integer idproducto, String nombreproducto, String descripcion, String precioproducto, String url, Integer items, String imagen, String relaciones, String tiendaNombre, Double precioDob, Double ahorro) {
       this.id = id;
       this.idlista = idlista;
       this.idproducto = idproducto;
       this.nombreproducto = nombreproducto;
       this.descripcion = descripcion;
       this.precioproducto = precioproducto;
       this.url = url;
       this.items = items;
       this.imagen = imagen;
       this.relaciones = relaciones;
       this.tiendaNombre = tiendaNombre;
       this.precioDob = precioDob;
       this.ahorro = ahorro;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getIdlista() {
        return this.idlista;
    }
    
    public void setIdlista(Integer idlista) {
        this.idlista = idlista;
    }
    public Integer getIdproducto() {
        return this.idproducto;
    }
    
    public void setIdproducto(Integer idproducto) {
        this.idproducto = idproducto;
    }
    public String getNombreproducto() {
        return this.nombreproducto;
    }
    
    public void setNombreproducto(String nombreproducto) {
        this.nombreproducto = nombreproducto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getPrecioproducto() {
        return this.precioproducto;
    }
    
    public void setPrecioproducto(String precioproducto) {
        this.precioproducto = precioproducto;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Integer getItems() {
        return this.items;
    }
    
    public void setItems(Integer items) {
        this.items = items;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public String getRelaciones() {
        return this.relaciones;
    }
    
    public void setRelaciones(String relaciones) {
        this.relaciones = relaciones;
    }
    public String getTiendaNombre() {
        return this.tiendaNombre;
    }
    
    public void setTiendaNombre(String tiendaNombre) {
        this.tiendaNombre = tiendaNombre;
    }
    public Double getPrecioDob() {
        return this.precioDob;
    }
    
    public void setPrecioDob(Double precioDob) {
        this.precioDob = precioDob;
    }
    public Double getAhorro() {
        return this.ahorro;
    }
    
    public void setAhorro(Double ahorro) {
        this.ahorro = ahorro;
    }




}


