package modelos;
// Generated 22/06/2018 12:17:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private String series;
     private String username;
     private String token;
     private Date lastUsed;

    public Login() {
    }

	
    public Login(String series) {
        this.series = series;
    }
    public Login(String series, String username, String token, Date lastUsed) {
       this.series = series;
       this.username = username;
       this.token = token;
       this.lastUsed = lastUsed;
    }
   
    public String getSeries() {
        return this.series;
    }
    
    public void setSeries(String series) {
        this.series = series;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    public Date getLastUsed() {
        return this.lastUsed;
    }
    
    public void setLastUsed(Date lastUsed) {
        this.lastUsed = lastUsed;
    }




}


