package modelos;
// Generated 26/11/2019 06:43:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pagina generated by hbm2java
 */
public class Pagina  implements java.io.Serializable {


     private int idpagina;
     private String nombreestablecimiento;
     private String descripcion;
     private Set subPaginas = new HashSet(0);

    public Pagina() {
    }

	
    public Pagina(int idpagina) {
        this.idpagina = idpagina;
    }
    public Pagina(int idpagina, String nombreestablecimiento, String descripcion, Set subPaginas) {
       this.idpagina = idpagina;
       this.nombreestablecimiento = nombreestablecimiento;
       this.descripcion = descripcion;
       this.subPaginas = subPaginas;
    }
   
    public int getIdpagina() {
        return this.idpagina;
    }
    
    public void setIdpagina(int idpagina) {
        this.idpagina = idpagina;
    }
    public String getNombreestablecimiento() {
        return this.nombreestablecimiento;
    }
    
    public void setNombreestablecimiento(String nombreestablecimiento) {
        this.nombreestablecimiento = nombreestablecimiento;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getSubPaginas() {
        return this.subPaginas;
    }
    
    public void setSubPaginas(Set subPaginas) {
        this.subPaginas = subPaginas;
    }




}


