package modelos;
// Generated 16/11/2019 08:26:25 PM by Hibernate Tools 4.3.1



/**
 * ProductoxcategoriaId generated by hbm2java
 */
public class ProductoxcategoriaId  implements java.io.Serializable {


     private int productoIdproducto;
     private int categoriaIdcategotia;

    public ProductoxcategoriaId() {
    }

    public ProductoxcategoriaId(int productoIdproducto, int categoriaIdcategotia) {
       this.productoIdproducto = productoIdproducto;
       this.categoriaIdcategotia = categoriaIdcategotia;
    }
   
    public int getProductoIdproducto() {
        return this.productoIdproducto;
    }
    
    public void setProductoIdproducto(int productoIdproducto) {
        this.productoIdproducto = productoIdproducto;
    }
    public int getCategoriaIdcategotia() {
        return this.categoriaIdcategotia;
    }
    
    public void setCategoriaIdcategotia(int categoriaIdcategotia) {
        this.categoriaIdcategotia = categoriaIdcategotia;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProductoxcategoriaId) ) return false;
		 ProductoxcategoriaId castOther = ( ProductoxcategoriaId ) other; 
         
		 return (this.getProductoIdproducto()==castOther.getProductoIdproducto())
 && (this.getCategoriaIdcategotia()==castOther.getCategoriaIdcategotia());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProductoIdproducto();
         result = 37 * result + this.getCategoriaIdcategotia();
         return result;
   }   


}


