package modelos;
// Generated 30/11/2019 06:41:14 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.Date;

/**
 * ProductoTwebscrHist generated by hbm2java
 */
public class ProductoTwebscrHist  implements java.io.Serializable {


     private int idproducto;
     @JsonIgnore
     private Tareawebscraper tareawebscraper;
     private String nombre;
     private String detalle;
     private Date fecha;
     private Date hora;
     private Date fechahora;
     private String direccionImagen;
     private Integer idcategoria;
     private String codigotienda;
     private String descripcion;
     private Double precio;
     private String url;
     private String relacion;
     private Boolean activo;
     private String tiendaNom;

    public ProductoTwebscrHist() {
    }

	
    public ProductoTwebscrHist(int idproducto, Date fecha, Date hora) {
        this.idproducto = idproducto;
        this.fecha = fecha;
        this.hora = hora;
    }
    public ProductoTwebscrHist(int idproducto, Tareawebscraper tareawebscraper, String nombre, String detalle, Date fecha, Date hora, Date fechahora, String direccionImagen, Integer idcategoria, String codigotienda, String descripcion, Double precio, String url, String relacion, Boolean activo, String tiendaNom) {
       this.idproducto = idproducto;
       this.tareawebscraper = tareawebscraper;
       this.nombre = nombre;
       this.detalle = detalle;
       this.fecha = fecha;
       this.hora = hora;
       this.fechahora = fechahora;
       this.direccionImagen = direccionImagen;
       this.idcategoria = idcategoria;
       this.codigotienda = codigotienda;
       this.descripcion = descripcion;
       this.precio = precio;
       this.url = url;
       this.relacion = relacion;
       this.activo = activo;
       this.tiendaNom = tiendaNom;
    }
   
    public int getIdproducto() {
        return this.idproducto;
    }
    
    public void setIdproducto(int idproducto) {
        this.idproducto = idproducto;
    }
    public Tareawebscraper getTareawebscraper() {
        return this.tareawebscraper;
    }
    
    public void setTareawebscraper(Tareawebscraper tareawebscraper) {
        this.tareawebscraper = tareawebscraper;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public Date getFechahora() {
        return this.fechahora;
    }
    
    public void setFechahora(Date fechahora) {
        this.fechahora = fechahora;
    }
    public String getDireccionImagen() {
        return this.direccionImagen;
    }
    
    public void setDireccionImagen(String direccionImagen) {
        this.direccionImagen = direccionImagen;
    }
    public Integer getIdcategoria() {
        return this.idcategoria;
    }
    
    public void setIdcategoria(Integer idcategoria) {
        this.idcategoria = idcategoria;
    }
    public String getCodigotienda() {
        return this.codigotienda;
    }
    
    public void setCodigotienda(String codigotienda) {
        this.codigotienda = codigotienda;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getRelacion() {
        return this.relacion;
    }
    
    public void setRelacion(String relacion) {
        this.relacion = relacion;
    }
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }
    public String getTiendaNom() {
        return this.tiendaNom;
    }
    
    public void setTiendaNom(String tiendaNom) {
        this.tiendaNom = tiendaNom;
    }




}


