package modelos;
// Generated 16/11/2019 08:26:25 PM by Hibernate Tools 4.3.1



/**
 * ProductoTiendaCadena generated by hbm2java
 */
public class ProductoTiendaCadena  implements java.io.Serializable {


     private int idproductoTiendaCadena;
     private Producto producto;
     private Tienda tienda;
     private String nombre;
     private Double valor;
     private Double valorUnidad;
     private Boolean estado;

    public ProductoTiendaCadena() {
    }

	
    public ProductoTiendaCadena(int idproductoTiendaCadena) {
        this.idproductoTiendaCadena = idproductoTiendaCadena;
    }
    public ProductoTiendaCadena(int idproductoTiendaCadena, Producto producto, Tienda tienda, String nombre, Double valor, Double valorUnidad, Boolean estado) {
       this.idproductoTiendaCadena = idproductoTiendaCadena;
       this.producto = producto;
       this.tienda = tienda;
       this.nombre = nombre;
       this.valor = valor;
       this.valorUnidad = valorUnidad;
       this.estado = estado;
    }
   
    public int getIdproductoTiendaCadena() {
        return this.idproductoTiendaCadena;
    }
    
    public void setIdproductoTiendaCadena(int idproductoTiendaCadena) {
        this.idproductoTiendaCadena = idproductoTiendaCadena;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Tienda getTienda() {
        return this.tienda;
    }
    
    public void setTienda(Tienda tienda) {
        this.tienda = tienda;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Double getValor() {
        return this.valor;
    }
    
    public void setValor(Double valor) {
        this.valor = valor;
    }
    public Double getValorUnidad() {
        return this.valorUnidad;
    }
    
    public void setValorUnidad(Double valorUnidad) {
        this.valorUnidad = valorUnidad;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


