package modelos;
// Generated Feb 5, 2019 12:28:51 AM by Hibernate Tools 4.3.1


import java.math.BigInteger;
import java.util.Date;

/**
 * ProductoTwebscrHist generated by hbm2java
 */
public class ProductoTwebscrHist  implements java.io.Serializable {


     private int idproducto;
     private String nombre;
     private String detalle;
     private Date fecha;
     private Date hora;
     private Date fechahora;
     private BigInteger idtarea;
     private String direccionimagen;
     private Integer idcategoria;
     private String codigotienda;
     private String descripcion;
     private Double precio;

    public ProductoTwebscrHist() {
    }

	
    public ProductoTwebscrHist(int idproducto, Date fecha, Date hora) {
        this.idproducto = idproducto;
        this.fecha = fecha;
        this.hora = hora;
    }
    public ProductoTwebscrHist(int idproducto, String nombre, String detalle, Date fecha, Date hora, Date fechahora, BigInteger idtarea, String direccionimagen, Integer idcategoria, String codigotienda, String descripcion, Double precio) {
       this.idproducto = idproducto;
       this.nombre = nombre;
       this.detalle = detalle;
       this.fecha = fecha;
       this.hora = hora;
       this.fechahora = fechahora;
       this.idtarea = idtarea;
       this.direccionimagen = direccionimagen;
       this.idcategoria = idcategoria;
       this.codigotienda = codigotienda;
       this.descripcion = descripcion;
       this.precio = precio;
    }
   
    public int getIdproducto() {
        return this.idproducto;
    }
    
    public void setIdproducto(int idproducto) {
        this.idproducto = idproducto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public Date getFechahora() {
        return this.fechahora;
    }
    
    public void setFechahora(Date fechahora) {
        this.fechahora = fechahora;
    }
    public BigInteger getIdtarea() {
        return this.idtarea;
    }
    
    public void setIdtarea(BigInteger idtarea) {
        this.idtarea = idtarea;
    }


    public String getDireccionimagen() {
        return direccionimagen;
    }

    public void setDireccionimagen(String direccionimagen) {
        this.direccionimagen = direccionimagen;
    }

    public Integer getIdcategoria() {
        return this.idcategoria;
    }
    
    public void setIdcategoria(Integer idcategoria) {
        this.idcategoria = idcategoria;
    }
    public String getCodigotienda() {
        return this.codigotienda;
    }
    
    public void setCodigotienda(String codigotienda) {
        this.codigotienda = codigotienda;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }




}


