package modelos;
// Generated 22/06/2018 12:17:42 PM by Hibernate Tools 4.3.1



/**
 * Productoxcategoria generated by hbm2java
 */
public class Productoxcategoria  implements java.io.Serializable {


     private ProductoxcategoriaId id;
     private Categoria categoria;
     private Producto producto;
     private Double valor;
     private Double valorUnidad;

    public Productoxcategoria() {
    }

	
    public Productoxcategoria(ProductoxcategoriaId id, Categoria categoria, Producto producto) {
        this.id = id;
        this.categoria = categoria;
        this.producto = producto;
    }
    public Productoxcategoria(ProductoxcategoriaId id, Categoria categoria, Producto producto, Double valor, Double valorUnidad) {
       this.id = id;
       this.categoria = categoria;
       this.producto = producto;
       this.valor = valor;
       this.valorUnidad = valorUnidad;
    }
   
    public ProductoxcategoriaId getId() {
        return this.id;
    }
    
    public void setId(ProductoxcategoriaId id) {
        this.id = id;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Double getValor() {
        return this.valor;
    }
    
    public void setValor(Double valor) {
        this.valor = valor;
    }
    public Double getValorUnidad() {
        return this.valorUnidad;
    }
    
    public void setValorUnidad(Double valorUnidad) {
        this.valorUnidad = valorUnidad;
    }




}


