package modelos;
// Generated 25/11/2019 06:05:58 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private int idproducto;
     private String nombre;
     private String detalle;
     private String direccionImagen;
     private Integer listaPredeterminada;
     @JsonIgnore
     private Set productoTiendas = new HashSet(0);
     @JsonIgnore
     private Set listaProductos = new HashSet(0);
     @JsonIgnore
     private Set productoTiendaCadenas = new HashSet(0);
     @JsonIgnore
     private Set productoxcategorias = new HashSet(0);
     private Double valor;

    public Producto() {
    }

	
    public Producto(int idproducto) {
        this.idproducto = idproducto;
    }
    public Producto(int idproducto, String nombre, String detalle, String direccionImagen, Integer listaPredeterminada, Set productoTiendas, Set listaProductos, Set productoTiendaCadenas, Set productoxcategorias) {
       this.idproducto = idproducto;
       this.nombre = nombre;
       this.detalle = detalle;
       this.direccionImagen = direccionImagen;
       this.listaPredeterminada = listaPredeterminada;
       this.productoTiendas = productoTiendas;
       this.listaProductos = listaProductos;
       this.productoTiendaCadenas = productoTiendaCadenas;
       this.productoxcategorias = productoxcategorias;
    }
   
    public int getIdproducto() {
        return this.idproducto;
    }
    
    public void setIdproducto(int idproducto) {
        this.idproducto = idproducto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public String getDireccionImagen() {
        return this.direccionImagen;
    }
    
    public void setDireccionImagen(String direccionImagen) {
        this.direccionImagen = direccionImagen;
    }
    public Integer getListaPredeterminada() {
        return this.listaPredeterminada;
    }
    
    public void setListaPredeterminada(Integer listaPredeterminada) {
        this.listaPredeterminada = listaPredeterminada;
    }
    public Set getProductoTiendas() {
        return this.productoTiendas;
    }
    
    public void setProductoTiendas(Set productoTiendas) {
        this.productoTiendas = productoTiendas;
    }
    public Set getListaProductos() {
        return this.listaProductos;
    }
    
    public void setListaProductos(Set listaProductos) {
        this.listaProductos = listaProductos;
    }
    public Set getProductoTiendaCadenas() {
        return this.productoTiendaCadenas;
    }
    
    public void setProductoTiendaCadenas(Set productoTiendaCadenas) {
        this.productoTiendaCadenas = productoTiendaCadenas;
    }
    public Set getProductoxcategorias() {
        return this.productoxcategorias;
    }
    
    public void setProductoxcategorias(Set productoxcategorias) {
        this.productoxcategorias = productoxcategorias;
    }


public Double getValor() {
        return valor;
    }

    public void setValor(Double valor) {
        this.valor = valor;
    }

}


