package modelos;
// Generated 27/11/2019 12:55:08 AM by Hibernate Tools 4.3.1



/**
 * UsuarioNew generated by hbm2java
 */
public class UsuarioNew  implements java.io.Serializable {


     private int id;
     private String keyUser;

    public UsuarioNew() {
    }

    public UsuarioNew(int id, String keyUser) {
       this.id = id;
       this.keyUser = keyUser;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getKeyUser() {
        return this.keyUser;
    }
    
    public void setKeyUser(String keyUser) {
        this.keyUser = keyUser;
    }




}


