package modelos;
// Generated 25/11/2019 06:05:58 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;

/**
 * UsuarioDireccion generated by hbm2java
 */
public class UsuarioDireccion  implements java.io.Serializable {


     private int idusuariodireccion;
     private Departamento departamento;
     private Municipio municipio;
     private Usuario usuario;
     private String direccion;
     private String nombredireccion;
     private double lat;
     private double lng;
     @JsonIgnore
     private Set listas = new HashSet(0);

    public UsuarioDireccion() {
    }

	
    public UsuarioDireccion(int idusuariodireccion, Departamento departamento, Municipio municipio, Usuario usuario, String direccion, String nombredireccion, double lat, double lng) {
        this.idusuariodireccion = idusuariodireccion;
        this.departamento = departamento;
        this.municipio = municipio;
        this.usuario = usuario;
        this.direccion = direccion;
        this.nombredireccion = nombredireccion;
        this.lat = lat;
        this.lng = lng;
    }
    public UsuarioDireccion(int idusuariodireccion, Departamento departamento, Municipio municipio, Usuario usuario, String direccion, String nombredireccion, double lat, double lng, Set listas) {
       this.idusuariodireccion = idusuariodireccion;
       this.departamento = departamento;
       this.municipio = municipio;
       this.usuario = usuario;
       this.direccion = direccion;
       this.nombredireccion = nombredireccion;
       this.lat = lat;
       this.lng = lng;
       this.listas = listas;
    }
   
    public int getIdusuariodireccion() {
        return this.idusuariodireccion;
    }
    
    public void setIdusuariodireccion(int idusuariodireccion) {
        this.idusuariodireccion = idusuariodireccion;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public Municipio getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(Municipio municipio) {
        this.municipio = municipio;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getNombredireccion() {
        return this.nombredireccion;
    }
    
    public void setNombredireccion(String nombredireccion) {
        this.nombredireccion = nombredireccion;
    }
    public double getLat() {
        return this.lat;
    }
    
    public void setLat(double lat) {
        this.lat = lat;
    }
    public double getLng() {
        return this.lng;
    }
    
    public void setLng(double lng) {
        this.lng = lng;
    }
    public Set getListas() {
        return this.listas;
    }
    
    public void setListas(Set listas) {
        this.listas = listas;
    }




}


