package modelos;
// Generated 25/11/2019 06:05:58 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * UsuarioNew generated by hbm2java
 */
public class UsuarioNew  implements java.io.Serializable {


     private long id;
     private Serializable key;

    public UsuarioNew() {
    }

    public UsuarioNew(long id, Serializable key) {
       this.id = id;
       this.key = key;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Serializable getKey() {
        return this.key;
    }
    
    public void setKey(Serializable key) {
        this.key = key;
    }




}


