package modelos;
// Generated 26/11/2019 06:43:24 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idusuario;
     private String nombre;
     private String apellido;
     private String email;
     private String clave;
     private Integer idtipodocumento;
     private String documento;
     private Short sexo;
     private Short estadocivil;
     private Date fechanacimiento;
     private String telefono;
     private short tipousuario;
     @JsonIgnore
     private Set listas = new HashSet(0);
     @JsonIgnore
     private Set usuarioDireccions = new HashSet(0);
     private Set listasCompartidases = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int idusuario, String nombre, String apellido, String email, String telefono, short tipousuario) {
        this.idusuario = idusuario;
        this.nombre = nombre;
        this.apellido = apellido;
        this.email = email;
        this.telefono = telefono;
        this.tipousuario = tipousuario;
    }
    public Usuario(int idusuario, String nombre, String apellido, String email, String clave, Integer idtipodocumento, String documento, Short sexo, Short estadocivil, Date fechanacimiento, String telefono, short tipousuario, Set listas, Set usuarioDireccions, Set listasCompartidases) {
       this.idusuario = idusuario;
       this.nombre = nombre;
       this.apellido = apellido;
       this.email = email;
       this.clave = clave;
       this.idtipodocumento = idtipodocumento;
       this.documento = documento;
       this.sexo = sexo;
       this.estadocivil = estadocivil;
       this.fechanacimiento = fechanacimiento;
       this.telefono = telefono;
       this.tipousuario = tipousuario;
       this.listas = listas;
       this.usuarioDireccions = usuarioDireccions;
       this.listasCompartidases = listasCompartidases;
    }
   
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public Integer getIdtipodocumento() {
        return this.idtipodocumento;
    }
    
    public void setIdtipodocumento(Integer idtipodocumento) {
        this.idtipodocumento = idtipodocumento;
    }
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }
    public Short getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Short sexo) {
        this.sexo = sexo;
    }
    public Short getEstadocivil() {
        return this.estadocivil;
    }
    
    public void setEstadocivil(Short estadocivil) {
        this.estadocivil = estadocivil;
    }
    public Date getFechanacimiento() {
        return this.fechanacimiento;
    }
    
    public void setFechanacimiento(Date fechanacimiento) {
        this.fechanacimiento = fechanacimiento;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public short getTipousuario() {
        return this.tipousuario;
    }
    
    public void setTipousuario(short tipousuario) {
        this.tipousuario = tipousuario;
    }
    public Set getListas() {
        return this.listas;
    }
    
    public void setListas(Set listas) {
        this.listas = listas;
    }
    public Set getUsuarioDireccions() {
        return this.usuarioDireccions;
    }
    
    public void setUsuarioDireccions(Set usuarioDireccions) {
        this.usuarioDireccions = usuarioDireccions;
    }
    public Set getListasCompartidases() {
        return this.listasCompartidases;
    }
    
    public void setListasCompartidases(Set listasCompartidases) {
        this.listasCompartidases = listasCompartidases;
    }




}


