"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 2.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'r&x5!r*5zs$8p+kgy-wxzf@*9ed^vx80n*fhv4(f!2@_ddm5p4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost','192.168.1.100','127.0.0.1','18.220.226.2','baratoapp.co','servicio.baratoapp.co']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'social_django',
    'widget_tweaks',
    'corsheaders',
    'rest_framework',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',

            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/



TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# use email as username
SOCIAL_AUTH_USERNAME_IS_FULL_EMAIL = True
#success Login redirect
LOGIN_REDIRECT_URL = 'index'
#login url
LOGIN_URL= '/sign_in'
#unic email
AUTH_USER_EMAIL_UNIQUE = True
#authentication backends for social networks
AUTHENTICATION_BACKENDS = (
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.google.GoogleOAuth',
    'app.backends.LoginEmailAndUsernameBackend', # it allows to authenticate using username or email
    'django.contrib.auth.backends.ModelBackend',

)
#social auth pipeline
SOCIAL_AUTH_PIPELINE=(

    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.social_auth.associate_by_email', 
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)
#common login redirect
LOGIN_REDIRECT_URL='index'

#social login redirect
SOCIAL_AUTH_LOGIN_REDIRECT_URL='index'
#facebook fields
SOCIAL_AUTH_FACEBOOK_IGNORE_DEFAULT_SCOPE = False
SOCIAL_AUTH_FACEBOOK_SCOPE = [
    'email'
]
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
  'locale': 'ru_RU',
  'fields': 'id, name, email, age_range'
}


#Facebook login credentials
#SOCIAL_AUTH_FACEBOOK_KEY='148834092471420'
#SOCIAL_AUTH_FACEBOOK_SECRET='16cccc06ee83af9ca9850fe3a4797963'
SOCIAL_AUTH_FACEBOOK_KEY='1790168647744823'
SOCIAL_AUTH_FACEBOOK_SECRET='dc92854216a32d4834cfda1ca72fea0c'

#Google login credentials
#SOCIAL_AUTH_GOOGLE_OAUTH2_KEY='856056632060-fvgisuhma7dkjbuqq3bot0vak300qb88.apps.googleusercontent.com'
#SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET='anQvCPJM3RWbzY9qn5zqz1Mr'
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY='737368835084-kvmucv5jai8tte8lcornqbsb2mjni1m8.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET='LoKrKgC2NZhUvsZjFXKmW0Lx'

#google configuration
SOCIAL_AUTH_GOOGLE_OAUTH2_USE_DEPRECATED_API = True
SOCIAL_AUTH_GOOGLE_PLUS_USE_DEPRECATED_API = True
SOCIAL_AUTH_GOOGLE_OAUTH2_IGNORE_DEFAULT_SCOPE = True
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
'https://www.googleapis.com/auth/userinfo.email',
'https://www.googleapis.com/auth/userinfo.profile'
]

#EMAIL configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com' # mail service smtp
#EMAIL_HOST_USER = 'robertosumoza@gmail.com' # email id
#EMAIL_HOST_PASSWORD = 'Electrica92' #password
EMAIL_HOST_USER = 'baratoappservicio@gmail.com' # email id
EMAIL_HOST_PASSWORD = 'Barato01&'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

SOCIAL_AUTH_REDIRECT_IS_HTTPS = True

